name: DesignPatterns-Test workflow

on:
  push:
    branches: [master]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: ["16"]
    steps:
      - uses: actions/checkout@v3
      - name: Setup node ${{ matrix.node }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
          cache: "npm"
      - name: Install dependencies
        run: npm install
      - name: Test project
        run: npm test
